### ISSUE TITLE
[Roadmap] GraphGym via PyTorch Lightning  🚀

### ISSUE THREAD

**Issue by aniketmaurya** [pyg-team/pytorch_geometric#4503]
### PyTorch Lightning Integration

[GraphGym](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/graphgym/train.py) training experience can be improved for scalability, mixed precision support, logging and checkpoints with [PyTorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning) integration.

* [x] Write [`LightningModule`](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html)
* [ ] Refactor `load_ckpt` and `save_ckpt` with PL checkpoint save and load method
* [x] Update [train](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/graphgym/train.py#L56) method with PL `Trainer` and the `LightningModule` implementation
* [ ] Integrate `LightningDataset`, `LightningNodeData` and `LightningLinkData` modules
* [ ] ...

**Comment by rusty1s** [comment]
Closing this issue in favor of https://github.com/pyg-team/pytorch_geometric/issues/5132. Thanks for your contributions @aniketmaurya. Hope you are also on board on future refactors of GraphGym :)
