### ISSUE TITLE
[Roadmap] Feature Store Integration

### ISSUE THREAD

**Issue by mananshah99** [pyg-team/pytorch_geometric#4806]
This is a brief summary of the roadmap required to integrate the [feature store](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/feature_store.py) abstraction into PyG, so that users can begin working with features stored out-of-core. More involved descriptions will accompany the closing PRs.

- [ ] Let `Data` and `HeteroData` implement the `FeatureStore` abstraction
- [ ] Define a `MaterializedGraph` abstraction that is intended to hold an `edge_index` in memory
- [ ] Let `Data` and `HeteroData` implement the `MaterializedGraph` abstraction
- [ ] Modify `NeighborLoader` to call `FeatureStore` and `MaterializedGraph` methods instead of their `Data/HeteroData` counterparts. Note that this will require moving filtering of data into the feature store. The new interface will look like `data: Union[Union[Data, HeteroData], Tuple[FeatureStore, MaterializedGraph]]`

**Comment by wsad1** [comment]
I think we should add this point to the roadmap
* Implement a concrete  `FeatureStore` using some "popular" storage backend.
This will help us "test" the interface, and also demonstrate how people can build concrete `FeatureStore`s.

**Comment by wsad1** [comment]
Also we could add
* Since `FeatureStore` and `MaterializedGraph` are independent. It would be nice to have `validate(FeatureStore, MaterializedGraph)` which checks things like 1.  `MaterializedGraph` only connects `node_type` present in `FeatureStore` 2. `max(edge_index)` is bounded by number of nodes in `FeatureStore`. 

`Validate` will mostly be a abstract class, with implementations over riding `__call__(FeatureStore, MaterializedGraph)`.

**Comment by rusty1s** [comment]
Yes, @wsad1. I think these are good points. One thing we could do to showcase is to have a short example/tutorial on how to connect to a neo4j graph database or similar.

**Comment by rusty1s** [comment]
Can we also add some clean up tasks here? For example, relying more on `FeatureStore` and `MaterializedGraph` interfaces than `BaseData`.

**Comment by mananshah99** [comment]
@rusty1s @wsad1 thanks for those suggestions, agreed on both fronts. Will incorporate tomorrow :)

**Comment by Padarn** [comment]
@mananshah99 just interested what you're planning for 
>  Implement a concrete FeatureStore and GraphStore with a popular backend to provide example usage
what backend are you thinking of supporting.

**Comment by Padarn** [comment]
(also I slightly updated the description to link to graphstore, hope you don't mind)

**Comment by mananshah99** [comment]
Hi folks, this roadmap has been updated a bit to describe latest changes and a few potential further directions (cc @Padarn, I hope this helps address some of your questions as well). Feel free to add on, or let me know if you have any questions/comments/concerns!

**Comment by Derek-Wds** [comment]
Hi team, I wonder if current remote backend can support edge features. It would be great if we can access edge features such as mult-iclass labels in the remote resources such as DBs.

**Comment by rusty1s** [comment]
cc @mananshah99

**Comment by AlexMRuch** [comment]
I love seeing Ray and Neo4j on these items! 😄

Are there any updates on these items? I don't see anything listed in the repo or in the docs.

I saw an example of using Kuzu for a Remote GraphStore (via `feature_store, graph_store = db.get_torch_geometric_remote_backend(mp.cpu_count())`) but not anything for Neo4j (except https://neo4j.com/docs/graph-data-science-client/current/tutorials/import-sample-export-gnn/, which is more complicated than the Kuzu counterpart).

Thanks in advance!
