### ISSUE TITLE
[Roadmap] GNN Explainability Support 🚀

### ISSUE THREAD

**Issue by RexYing** [pyg-team/pytorch_geometric#5520]
### 🚀 The feature, motivation and pitch

Explainability has been an important component for users to probe model behavior, understand feature and structural importances, obtain new knowledge about the underlying task, and extract insights from a GNN model. 

Over the years, many papers on GNN explainability have been published (some of which are integrated into PyG already), and many surveys, benchmakrs and evaluation frameworks have been proposed, such as the [taxonomic survey](https://arxiv.org/abs/2012.15445) and [GraphFramEx](https://arxiv.org/abs/2206.09677) multi-aspect evaluation framework. Some of these recent progress raise new challenges in terms of method, evaluation and visualization, outlined here.

- [x] A high-level explainability support framework to support explainability methods in PyG. For example, for post-hoc explanations, we can generally classify existing techniques into gradient-based techniques (such as saliency and gradcam), perturbation-based techniques (such as GNNExplainer, PGExplainer). We can provide a unified interface to invoke these explanation methods given an instance or a group of instances given a model and the instance(s) that we want to explain. 
- [x] Move existing implementations to the new unified interface
- [x] Provide support for synthetic datasets commonly used in explainability papers. #5817
- [x] Provide basic evaluation metrics, such as fidelity+/- measures ([taxonomic survey](https://arxiv.org/abs/2012.15445), [GraphFramEx](https://arxiv.org/abs/2206.09677)) to evaluate the quality of explanations. #5628 
- [x] Support different explanation evaluation based on hard / soft masks; explanation of phenomenon vs. model etc. ([GraphFramEx](https://arxiv.org/abs/2206.09677)). #5629 
- [x] Provide support for different explainability methods (SubgraphX, PGExplainer, ...)
- [x] Explainability support for heterogeneous graphs. There exist simple ways to adapt current explainability methods into heterogeneous graphs. For example, we can use gradient-based methods by taking gradient with respect to adjacencies (edge_index) of different message types. We can also adapt GNNExplainer by creating a mask corresponding to each of the edge_index for different message types. #5630
- [ ] Explainability support for other types of graph modalities supported by PyG, such as bipartite graphs.
- [x] Improve visualization utility functions of the explanation. It can be in the form of feature importance maps, or visualization of the explanation subgraph. Support parameters such as the size of explanation and show weighted importance for edges to control the visualization output. #5631 
- [ ] Notebook Demo, Example script
- [x] Documentation, Tutorials

### Additional context

There are other explainability functionalities that are still in relatively early stage, such as concept / class-wise explanations and counterfactual explanations. There are ongoing research projects that could potentially be integrated in future.

**Comment by Padarn** [comment]
This sounds pretty cool, I'd be keen to lend a hand :-) 

FYI: There is an open PR that is quite related https://github.com/pyg-team/pytorch_geometric/pull/4507.

**Comment by wsad1** [comment]
Thanks for adding the roadmap. 
One complexity with `Explainability support for heterogeneous graphs` is as follows:
Methods like `GNNExplainer` work by setting a mask in the `MessagePassing` module https://github.com/pyg-team/pytorch_geometric/blob/d8d06e1b69bea4e71ab39c141aa00a17c32d72d9/torch_geometric/nn/models/explainer.py#L13. 
This might be an issue for methods like `HanConv` and `HGTConv` as internally they share a `MessagePassing` module across edge types, so we won't be able to set separate masks for each edge type. One way to resolve this is to refactor these gnns to have a different message module for each edge type.

**Comment by Padarn** [comment]
That makes sense @wsad1, I think for most common cases using something like `to_hetero` this won't be a problem, but I guess the models that are doing this today would need to be updated. 

Possibly even just setting a 'explainability_disabled' on those models would be enough?

**Comment by divyanshugit** [comment]
@RexYing If possible, I would love to work on adding basic evaluation metrics. Please let me know if no one is working on it.

**Comment by rusty1s** [comment]
No one is working on this yet, so please feel free to go ahead. Much appreciated, thank you!

**Comment by RexYing** [comment]
@divyanshugit Happy to setup a meeting to discuss more in detail. I'll reach out to you on PyG Slack. As suggested by @ivaylobah , I'll break it down into several issues. The issue that you might be able to start is https://github.com/pyg-team/pytorch_geometric/issues/5628.

**Comment by divyanshugit** [comment]
> @divyanshugit Happy to setup a meeting to discuss more in detail. I'll reach out to you on PyG Slack. As suggested by @ivaylobah , I'll break it down into several issues. The issue that you might be able to start is #5628.

Thank you so much for the reminder. It would be great to discuss this in detail.

**Comment by musicjae** [comment]
I'm passionate to this plan. It's cool

**Comment by daniel-unyi-42** [comment]
I'd be happy to work on this, especially these two:
- Provide support for different explainability methods (SubgraphX, PGExplainer, ...)
- Improve visualization utility functions of the explanation. It can be in the form of feature importance maps, or visualization of the explanation subgraph. Support parameters such as the size of explanation and show weighted importance for edges to control the visualization output.
Which task would be the most helpful if I worked on it? @RexYing @rusty1s

**Comment by rusty1s** [comment]
Thanks @daniel-unyi-42. We are launching an explainability sprint with more fine-granular tasks soon. Please consider participating!
