### ISSUE TITLE
[Community Sprint] Add missing type hints and TorchScript support 🚀

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#5657]
### 🚀 The feature, motivation and pitch

**We are kicking off our very first community sprint!**

The community sprint resolves around **adding missing type hints and TorchScript support** for various functions across PyG, aiming to improve and clean-up our core codebase. Each individual contribution is designed to only take **around 30 minutes to two hours** to complete.

The sprint begins **Wednesday October 12th** with a kick off meeting at 8am PST. The community sprint will **last 2 weeks** and we will have another live hangouts when the sprint has completed. If you are interested in helping out, please also join our **[PyG slack](https://data.pyg.org/slack.html) channel `#community-sprint-type-hints`** for more information. **You can assign yourself to the type hints you are planning to work on [here](https://docs.google.com/spreadsheets/d/1QpwREo8_iQ0sfnXCa22i1b1XEM9Udxu7X16Z77eyRg8/edit?usp=sharing).**

# 🚀 Add missing type hints and TorchScript support

Type hints are currently used inconsistently in the `torch-geometric` repository, and it would be nice to make them a complete, consistent thing across all datasets, models and utilities. Adding type hint support in models also helps us to improve our TorchScript coverage across layers and models provided in `nn.*`.

## Example

Take a look at the current implementation of [`contains_isolated_nodes`](https://github.com/pyg-team/pytorch_geometric/blob/56610200da56fc43ae7ba4ed27b207cae6c7613c/torch_geometric/utils/isolated.py#L8):

```python
def contains_isolated_nodes(edge_index, num_nodes=None):
    num_nodes = maybe_num_nodes(edge_index, num_nodes)
    edge_index, _ = remove_self_loops(edge_index)
    return torch.unique(edge_index.view(-1)).numel() < num_nodes
 ```
 
 Adding type hints support to the function signature helps us to better understand its input and output, improving code readability:
 
 ```python
def contains_isolated_nodes(
    edge_index: Tensor,
    num_nodes: Optional[int] = None,
) -> bool:
    ...
```

Importantly, it also lets us use it as part of a TorchScript model. Without it, all arguments that miss type hints are expected to be PyTorch tensors (which is clearly not the case for the `num_nodes` argument). Without it, `torch.jit.script` compilation will fail:

```python
import torch

from torch_geometric.utils import contains_isolated_nodes

contains_isolated_nodes = torch.jit.script(contains_isolated_nodes)

contains_isolated_nodes(torch.tensor([[0, 1, 0], [1, 0, 0]])
```

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File ".../pytorch_geometric/torch_geometric/utils/isolated.py", line 29, in contains_isolated_nodes
    num_nodes = maybe_num_nodes(edge_index, num_nodes)
                ~~~~~~~~~~~~~~~ <--- HERE
    edge_index, _ = remove_self_loops(edge_index)
    return torch.unique(edge_index.view(-1)).numel() < num_nodes
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument
```

## Guide to contributing

**See [here](https://github.com/pyg-team/pytorch_geometric/pull/5603) for a basic example to follow**.

1. Ensure you have read our [contributing guidelines](https://github.com/pyg-team/pytorch_geometric/blob/master/CONTRIBUTING.md).
2. Claim the functionality/model you want to improve **[here](https://docs.google.com/spreadsheets/d/1QpwREo8_iQ0sfnXCa22i1b1XEM9Udxu7X16Z77eyRg8/edit?usp=sharing)**.
3. Implement the  changes as in https://github.com/pyg-team/pytorch_geometric/pull/5603. At best, ensure in a test that the model/function is convertable to a TorchScript program and that it results in the *same* output. It is okay to add type hint support for multiple functions/models within a single PR as long as you have assigned yourself to each of them, and the number of file changes stays at a reasonable number to ease reviewing (*e.g.*, not more than 10 touched files).
4. Open a PR to the PyG repository and name it: **"[Type Hints] `{model_name/function_name}`"**. In addition, ensure that documentation is rendered properly (CI will build the documentation automatically for you). Afterwards, add your PR number to the ["Improved type hint support" line](https://github.com/pyg-team/pytorch_geometric/blob/292e289839a5a94bbc04494bcab3f4ac95086fcc/CHANGELOG.md?plain=1#L39) in `CHANGELOG.md`.

## Tips for making your PR

* If you are unfamiliar with how type hints work, you can read the [Python library documentation](https://docs.python.org/3/library/typing.html) on them, but it is probably even easier to just look at another PR that added them.
* The types will usually be obvious, *e.g.*, `Tensor`, `bool`, `int`, `float`. Wrap them within `Optional[*]` whenever the argument can be `None`.
* Specialized PyG type hints (*e.g.*, `Adj`) are defined in [`typing.py`](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/typing.py).
* In some rare cases, type hints are challenging to add, *e.g.*, whenever a model/function supports a `Union` of different types (which may be the case for functions/models that also support `SparseTensor`, *e.g.*, `edge_index: Union[Tensor, SparseTensor]`). In that case, TorchScript support can be achieved via the `torch.jit._overload` decorator. See [here](https://github.com/pyg-team/pytorch_geometric/blob/56610200da56fc43ae7ba4ed27b207cae6c7613c/torch_geometric/nn/conv/gcn_conv.py#L18-L33) for an example.
* The corresponding tests of PyG models and functions can be found in the `test/` directory. For example, tests for `torch_geometric/utils/isolated.py` can be found in `test/utils/test_isolated.py`. You can run individual test files via `pytest test/utils/test_isolated.py`. It is only necessary to test TorchScript support for the `nn.*` and `utils.*` packages. No changes necessary for `datasets.*` and `transforms.*` packages.
* Ensure that the TorchScript variant compiles and achieves the same output:
  ```python
  from torch_geometric.testing import is_full_test

  ...

  edge_index = torch.tensor([[0, 1, 2, 0], [1, 0, 2, 0]])
  assert contains_isolated_nodes(edge_index)
    
  if is_full_test():
      jit = torch.jit.script(contains_isolated_nodes)
      assert jit(edge_index)
  ```
  Note that we generally gate TorchScript tests behind `is_full_test()` which guarantees that TorchScript tests are only run nightly. You can enable full tests locally via the `FULL_TEST=1` environment variable, *e.g.*, `FULL_TEST=1 pytest test/utils/test_isolated.py`. It is only necessary to ensure TorchScript support for the `nn.*` and `utils.*` packages. No changes necessary for `datasets.*` and `transforms.*` packages.
  
## Functions/Models to update

This list may be incomplete. If you still find a function without missing type hints/TorchScript tests, please let us know or add them on your own.

* [x] `nn.MetaLayer` (#5758)
* [x] `nn.ChebConv` (#5730)
* [x] `nn.InstanceNorm` (#5684)
* [x] `nn.GraphSizeNorm` (#5729)
* [x] `nn.MessageNorm` (#5847)
* [x] `nn.DiffGroupNorm` (#5757)
* [x] `nn.TopKPooling` (#5731)
* [x] `nn.SAGPooling` (#5810)
* [x] `nn.EdgePooling` (#5738)
* [x] `nn.PANPooling` (#5852)
* [x] `nn.max_pool` (#5735)
* [x] `nn.avg_pool` (#5734)
* [x] `nn.max_pool_x` (#5687)
* [x] `nn.max_pool_neighbor_x` (#5703)
* [x] `nn.avg_pool_x` (https://github.com/pyg-team/pytorch_geometric/pull/5706)
* [x] `nn.avg_pool_neighbor_x` (#5707)
* [x] `nn.Node2Vec` (#5669)
* [x] `nn.DeepGraphInfomax` (#5688)
* [x] `nn.InnerProductDecoder` (#5842)
* [x] `nn.GAE` (#5842)
* [x] `nn.VGAE` (#5842)
* [x] `nn.ARGA` (#5726)
* [x] `nn.ARGVA` (#5726)
* [x] `nn.SignedGCN` (#5725)
* [x] `nn.RENet` (#5715)
* [x] `nn.GraphUNet` (#5710)
* [x] `nn.SchNet` (#5710)
* [x] `nn.DimeNet` (#5806)
* [x] `nn.DimeNetPlusPlus` (#5806)
* [x] `nn.GNNExplainer` (#5716)
* [x] `nn.DeepGCNLayer` (#5699)
* [x] `nn.AttentiveFP`(#5766)
* [x] `nn.DenseGCNConv` (#5664)
* [x] `nn.DenseGINConv` (#5842)
* [x] `nn.DenseGraphConv` (#5842)
* [x] `nn.DenseSAGEConv` (#5664)
* [x] `nn.dense_diff_pool` (#5754)
* [x] `nn.dense_mincut_pool` (#5756)
* [x] `datasets.NELL` (#5678)
* [x] `datasets.PPI` (#5678)
* [x] `datasets.Reddit` (#5695)
* [x] `datasets.Reddit2` (#5695)
* [x] `datasets.Yelp` (#5747)
* [x] `datasets.QM7b` (#5678)
* [x] `datasets.ZINC` (#5678)
* [x] `datasets.MoleculeNet` (#5678)
* [x] `datasets.MNISTSuperpixels` (#5760)
* [x] `datasets.ShapeNet` (#5828)
* [x] `datasets.ModelNet` (#5701)
* [x] `datasets.SHREC2016` (#5798)
* [x] `datasets.TOSCA` (#5797)
* [x] `datasets.PCPNetDataset` (#5797)
* [x] `datasets.S3DIS` (#5799)
* [x] `datasets.ICEWS18` (#5666)
* [x] `datasets.WILLOWObjectClass` (#5781)
* [x] `datasets.PascalVOCKeypoints` (#5781)
* [x] `datasets.PascalPF` (#5781)
* [x] `datasets.SNAPDataset` (#5811)
* [x] `datasets.SuiteSparseMatrixCollection` (#5811)
* [x] `datasets.WordNet18` (#5811)
* [x] `datasets.WordNet18RR` (#5811)
* [x] `datasets.WebKB` (#5778)
* [x] `datasets.JODIEDataset` (#5797)
* [x] `datasets.MixHopSyntheticDataset` (#5797)
* [x] `datasets.UPFD` (#5800)
* [x] `transforms.Distance` (#5685)
* [x] `transforms.Cartesian` (#5673)
* [x] `transforms.LocalCartesian` (#5675)
* [x] `transforms.Polar` (#5676)
* [x] `transforms.Spherical` (#5732)
* [x] `transforms.PointPairFeatures` (#5732)
* [x] `transforms.OneHotDegree` (#5667)
* [x] `transforms.TargetIndegree` (#5743)
* [x] `transforms.RandomJitter` (#5714)
* [x] `transforms.RandomFlip` (#5714)
* [x] `transforms.RandomScale` (#5714)
* [x] `transforms.RandomRotate` (#5714)
* [x] `transforms.RandomShear` (https://github.com/pyg-team/pytorch_geometric/pull/5702/)
* [x] `transforms.KNNGraph` (#5722)
* [x] `transforms.FaceToEdge` (#5722)
* [x] `transforms.SamplePoints` (#5733)
* [x] `transforms.FixedPoints` (#5733)
* [x] `transforms.ToDense` (#5668)
* [x] `transforms.LaplacianLambdaMax` (#5733)
* [x] `transforms.ToSLIC` (#5743)
* [x] `transforms.GDC` (#5752)
* [x] `transforms.SIGN` (#5736)
* [x] `transforms.SVDFeatureReduction` (#5743)
* [x] `transforms.AddSelfLoops` (#5753)
* [x] `transforms.Center` (#5753)
* [x] `transforms.Compose` (#5753)
* [x] `transforms.Delaunay` (#5753)
* [x] `transforms.GCNNorm` (#5753)
* [x] `transforms.GenerateMeshNormals` (#5753)
* [x] `transforms.LinearTransformation` (#5753)
* [x] `transforms.LocalDegreeProfile` (#5753)
* [x] `transforms.NormalizeFeatures` (#5753)
* [x] `transforms.NormalizeRotation` (#5753)
* [x] `transforms.NormalizeScale` (#5753)
* [x] `transforms.RadiusGraph` (#5753)
* [x] `transforms.RandomLinkSplit` (#5753)
* [x] `transforms.RandomNodeSplit` (#5753)
* [x] `transforms.RemoveIsolatedNodes` (#5753)
* [x] `transforms.ToDevice` (#5753)
* [x] `transforms.ToSparseTensor` (#5753)
* [x] `transforms.ToUndirected` (#5753)
* [x] `transforms.TwoHop` (#5753)
* [x] `utils.remove_isolated_nodes` (#5659)
* [x] `utils.get_laplacian` (#5682)
* [x] `utils.to_dense_adj` (#5682)
* [x] `utils.dense_to_sparse` (#5683)
* [x] `utils.normalized_cut` (#5665)
* [x] `utils.grid` (#5724)
* [x] `utils.geodesic_distance` (#5851)
* [x] `utils.tree_decomposition` (#5851)
* [x] `utils.to_scipy_sparse_matrix` (#5736)
* [x] `utils.from_scipy_sparse_matrix` (#5736)
* [x] `utils.to_networkx` (#5768)
* [x] `utils.from_networkx` (#5768)
* [x] `utils.erdos_renyi_graph` (#5768)
* [x] `utils.stochastic_blockmodel_graph` (#5768)
* [x] `utils.barabasi_albert_graph` (#5768)
* [x] `utils.train_test_split_edges` (#5737)

**Comment by rusty1s** [comment]
@EdisonLeeeee Sounds great. Please add yourself to the [Google Sheet doc](https://docs.google.com/spreadsheets/d/1QpwREo8_iQ0sfnXCa22i1b1XEM9Udxu7X16Z77eyRg8/edit#gid=0), but please leave room for other people to participate as well.

**Comment by venomouscyanide** [comment]
@rusty1s is `nn.InnerProductEncoder` supposed to be `nn.InnerProductDecoder` ? Not sure where `nn.InnerProductEncoder` is present in the codebase.

**Comment by rusty1s** [comment]
@venomouscyanide This is indeed a typo, good catch. Fixed :)

**Comment by EdisonLeeeee** [comment]
@rusty1s I found some of the classes in `transforms.*` is missing (partially) type hints, e.g., `transforms.Center` and `transforms.AddSelfLoops`, which are not mentioned in this issue. Shall we also add type hints for them?

**Comment by rusty1s** [comment]
Yeah, if you have found some transforms not included here, please add them to the list :)

**Comment by rusty1s** [comment]
**We reached 100% coverage of the community sprint! :tada:** This is amazing to see! I like to deeply thank everyone who participated in this sprint. Thanks for improving our code base and for contributing to PyG!
