### ISSUE TITLE
[Community Sprint] Improving Code Coverage 🚀

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#6528]
### 🚀 The feature, motivation and pitch

**We are kicking off our third community sprint!**

This community sprint resolves around **improving test coverage** across the PyG code base.
Currently, our [tests cover 85.68%](https://app.codecov.io/gh/pyg-team/pytorch_geometric/tree/master/torch_geometric) of all code in PyG. The goal of the community sprint is to bump this number into the high 90s (and to get yourself more familiar with the various parts of the code base). Each individual contribution is designed to only take **around 30 minutes to two hours** to complete.

The sprint begins **Friday Janurary 27th** and will **last 2 weeks**. If you are interested in helping out, please also join our **[PyG slack](https://data.pyg.org/slack.html) channel `#code-coverage-sprint`** for more information.

**You can assign yourself to the test you are planning to work on [here](https://docs.google.com/spreadsheets/d/1QpwREo8_iQ0sfnXCa22i1b1XEM9Udxu7X16Z77eyRg8/edit#gid=1220861398) (code-coverage tab)**.

# 🚀 Improving Code Coverage

## Example

Take a look at the current [code coverage report](https://app.codecov.io/gh/pyg-team/pytorch_geometric/tree/master/torch_geometric) of PyG. For example, we can see that we never test the [`copy()`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.InMemoryDataset.html#torch_geometric.data.InMemoryDataset.copy) function of the [`InMemoryDataset`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.InMemoryDataset.html#torch_geometric.data.InMemoryDataset) class, see [here](https://app.codecov.io/gh/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/in_memory_dataset.py):

![Screenshot 2023-01-26 at 15 51 43](https://user-images.githubusercontent.com/6945922/215070701-5d23382a-b194-4cb4-964e-7e7356ee5197.png)

As such, we create a `test_in_memory_dataset_copy()` function in `test/data/test_dataset.py` to add a corresponding test:

```python
def test_in_memory_dataset_copy():
    data_list = [Data(x=torch.randn(5, 16)) for _ in range(4)]
    dataset = MyTestDataset(data_list)

    copied_dataset = dataset.copy()

    # Test that we actually do a copy:
    assert id(copied_dataset) != id(dataset)

    # Test that the copied dataset holds the same objects:
    assert len(copied_dataset) == len(dataset) == 4
    
    # Tests that the data is identical:
    for copied_data, data in zip(copied_dataset, dataset):
        assert torch.equal(copied_data.x, data.x)
```

Furthermore, we see in the [code coverage report](https://app.codecov.io/gh/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/in_memory_dataset.py) that `copy()` utilizes different code paths, depending on whether the dataset should be filtered before copying. As such, we test this functionality as well:

```python
def test_in_memory_dataset_copy():
    ...
    
    copied_dataset = dataset.copy([1, 2])
    assert len(copied_dataset) == 2
    assert torch.equal(copied_dataset[0].x, data_list[1].x)
    assert torch.equal(copied_dataset[1].x, data_list[2].x)
```

We can check that everything works by running `pytest test/data/test_dataset.py -k test_in_memory_dataset_copy`:

```
test/data/test_dataset.py .

========================== 1 passed, 9 deselected in 0.07s =========================
```

## Guide to contributing

**See [here](https://github.com/pyg-team/pytorch_geometric/pull/6523) for a basic example to follow**.

1. Ensure you have read our [contributing guidelines](https://github.com/pyg-team/pytorch_geometric/blob/master/CONTRIBUTING.md).
2. Claim the test you want to improve **[here](https://docs.google.com/spreadsheets/d/1QpwREo8_iQ0sfnXCa22i1b1XEM9Udxu7X16Z77eyRg8/edit#gid=1220861398) (code coverage tab)**.
3. Implement the test changes as in https://github.com/pyg-team/pytorch_geometric/pull/6523. For this, look closely at the parts of a model and function you want to cover. Think about test cases that would increase the coverage. If you stumble upon a bug in untested code paths, try to fix the bug on your own, [**create a GitHub issue**](https://github.com/pyg-team/pytorch_geometric/issues/new/choose) or discuss it with us in our **[PyG slack](https://data.pyg.org/slack.html) channel `#code-coverage-sprint`**.
4. Open a PR to the PyG repository and name it: **"[Code Coverage] `{model_name/function_name}`"**. Afterwards, add your PR number to the "Improved code coverage" line in `CHANGELOG.md`.

## Tips for making your PR

* If you are unfamiliar with how the current test pipeline works, you can read more about it [here](https://github.com/pyg-team/pytorch_geometric/blob/master/CONTRIBUTING.md#unit-testing). We use [`pytest`](https://docs.pytest.org/en/7.2.x/) to run all tests.
* The corresponding tests of PyG models and functions can be found in the `test/` directory. For example, tests for [`torch_geometric/utils/isolated.py`](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/isolated.py) can be found in [`test/utils/test_isolated.py`](https://github.com/pyg-team/pytorch_geometric/blob/master/test/utils/test_isolated.py). You can run individual test files via `pytest test/utils/test_isolated.py`. You can run individual test functions via `pytest test/utils/test_isolated.py -k test_contains_isolated_nodes`.
* You can use `@pytest.mark.parametrize('arg_name', [1, 2, 3])` to test different configurations inside your test. See [here](https://github.com/pyg-team/pytorch_geometric/blob/master/test/nn/aggr/test_basic.py#L34) for an example.
* There exists special test decorators for testing in [`torch_geometric/testing/decorators.py`](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/testing/decorators.py), *e.g.*, to only run with specific packages installed via the `@withPackage('networkx')` decorator.
* For code paths that are nearly impossible to test, consider adding a `# pragma: no cover` comment, *e.g.*, `@overload` routines
  
## Tests to update

This list may be incomplete. If you still find a function with missing code coverage, please let us know or add them on your own.

* [x] `data/lightning/datamodule.py` (#6858)
* [x] `data/data.py` (#8074)
* [x] `data/datapipes.py` (#6799, #7195)
* [ ] `data/dataset.py`
* [x] `data/feature_store.py` (#6678)
* [x] `data/graph_store.py` (#6720)
* [x] `data/hetero_data.py` (#8074)
* [x] `data/storage.py` (#6677)
* [x] `data/temporal.py` (#6735)
* [x] `data/view.py` (#7093)
* [ ] `explain/explainer.py`
* [x] `explain/gnn_explainer.py` (#6676)
* [x] `explain/attention_explainer.py` (#6667)
* [x] `explain/captum_explainer.py` (#6797)
* [x] `explain/pg_explainer.py` (#6824)
* [x] `loader/dataloader.py` (#6648)
* [x] `loader/imbalanced_sampler.py` (#6664)
* [x] `loader/utils.py` (#7857)
* [x] `loader/temporal_dataloader.py` (#7968)
* [x] `loader/neighbor_sampler.py` (#6538)
* [x] `profile/profile.py` (#6555)
* [x] `profile/profiler.py` (#6573)
* [x] `profile/utils.py` (#6618)
* [ ] `sampler/utils.py`
* [x] `utils/assortativity.py` (#6578)
* [x] `utils/convert.py` (#6653)
* [x] `utils/loop.py` (#6647)
* [x] `utils/negative_sampling.py` (#6619)
* [x] `utils/num_nodes.py`(#6669)
* [x] `transforms/compose.py` (#7937)
* [x] `transforms/add_self_loops.py` (#6668)
* [x] `transforms/largest_connected_components.py` (#6670)
* [x] `transforms/linear_transformation.py` (#6657)
* [x] `transforms/random_link_split.py` (#6671)
* [x] `transforms/remove_traning_classes.py` (#6640)
* [x] `transforms/sign.py` (#6683)
* [x] `transforms/svd_feature_reduction.py` (#6736)
* [x] `transforms/to_device.py` (#6621)
* [x] `transforms/gcn_norm.py` (#6673)
* [x] `nn/conv/appnp.py` (#6558)
* [x] `nn/conv/eg_conv.py` (#8074)
* [x] `nn/conv/fa_conv.py` (#6681)
* [x] `nn/conv/gen_conv.py` (#6703)
* [x] `nn/conv/hetero_conv.py` (#6568)
* [x] `nn/conv/pna_conv.py` (#6600)
* [x] `nn/conv/rgat_conv.py` (#7937)
* [x] `nn/conv/transformer_conv.py` (#7968)
* [x] `nn/aggr/scaler.py` (#6600)
* [ ] `nn/dense/linear.py`
* [x] `nn/models/correct_and_smooth.py` (#6637)
* [x] `nn/models/dimenet.py` (#6781)
* [x] `nn/models/label_prob.py` (#6597)
* [x] `nn/models/rect.py` (#6623)
* [x] `nn/models/schnet.py` (#6763)
* [x] `nn/models/tgn.py` (#6662)
* [x] `nn/inits.py` (#6645)
* [ ] `experimental.py`
* [x] `home.py` (#6638)
