### ISSUE TITLE
[Roadmap] CPU Performance Optimization for PyG at PyTorch 2.x

### ISSUE THREAD

**Issue by mingfeima** [pyg-team/pytorch_geometric#7057]
### 🚀 The feature, motivation and pitch

With compiler feature added in torch 2.0, it is worthy to continue the optimization project for PyG with the new features.

### Functionality and Profiling

- [ ] add `compile` option in current pyg benchmarks and fix feature gaps on cpu backend.
- [ ] CPU profiling with eager mode and compiled mode, including **inference** and **training**.

### Performance Optimization

Generally, there are two sets of approaches for optimization on cpu backend: a) explicit fusion, usually with library support; b) pointwise Op fusion in torch inductor.

- [ ] **scatter_add/scatter_reduce**: this one can be fused via inductor, but generated code for GNN use case is not optimal. The generated kernel would use `atomic` to handle the write conflicts when paralleling on the outer dimension. Need to map optimal algorithm to inductor.
- [ ] **gather**: backward performance is troublesome in compiler.
- [ ] **sparse.mm(reduce)**: this one cannot be fused with other Ops right now, need to add explicit fusion. The first step would be collect the fusion pattern.
- [ ] **sampled_addmm**[TBD]: need explicit fusion, collect fusion pattern at the first step.

And in the long term, it is more reasonable to skip overloading `torch.compile` in pyg.

### Some leftovers from 1st stage:

- [ ] optimize torch.sort (map **index_sort**).
- [ ] **sparse.mm(reduce)** backward performance regression.
- [ ] bfloat16/float16 optimization.
- [ ] add reduce flag of **std**.
- [ ] add multi-aggregation mode.
