### ISSUE TITLE
[Roadmap] Better support for hypergraphs

### ISSUE THREAD

**Issue by wsad1** [pyg-team/pytorch_geometric#7312]
### 🚀 The feature, motivation and pitch

Following this [discussion](https://github.com/pyg-team/pytorch_geometric/discussions/7120). The goal is to improve support for hypergraphs in pyg via:

- [x]  Add `HyperGraphData` object that inherits from `BaseData` and implements `__inc__`, `__cat_dim__`, `num_nodes`, `subgraph` etc for hyper graphs. The `hyperedge_index` will be of shape `[2, num_hyper_edges*num_nodes_per_hyper_edge]`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.HypergraphConv.html#torch_geometric.nn.conv.HypergraphConv) for an example.[#7611]
- [x] Test that `DataLoader` works with `HyperGraphData`. [#7611]
- [x] Add a hyper graph dataset to `Datasets`
- [ ] Add hyper graph gnns like [HGNN](https://arxiv.org/abs/1809.09401), 
- [ ] Add an example that uses all of the above new modules.

**Comment by CodeTal** [comment]
@wsad1 Hello sir, I am a new open-source contributor and PyG user. I happened to see this issue and found that the hypergraph is a really interesting notion. Could I work on this issue?

**Comment by CodeTal** [comment]
@rusty1s OK. I will try to do something these days.

**Comment by CodeTal** [comment]
@rusty1s Thank you for letting me know!

**Comment by CodeTal** [comment]
Hello, I am trying to implement the HyperGraphData class first. I have gone through some relevant codes and formulated some initial ideas. I think most functions can be inherited from the Data class, and here are something that we need to change:

1. Re-name some parameters. For example, edge_index to hyperedge_index, adj to incidence
2. Re-implement some functions. 
- Prior issues (#7365）mentioned that the \_\_inc\_\_ function should be refactored. Based on my understanding of how the tensors are collated during batching, the \_\_inc\_\_ of HyperGraphData should still return the num_nodes for the first row of hyperedge_index but return the num_hyperedges for the second row of hyperedge_index. 
- The \_\_cat_dim\_\_ function could remain the same as the concatenation method doesn't change. 
- The subgraph function should be changed because the expression of edge_index has changed.
- Other functions could remain the same as the original Data class.

I am new to this project, so I still have many confusions. If I am wrong, could you please provide some feedback when you are free? Thanks a lot!

**Comment by wsad1** [comment]
@CodeTal Thanks for showing interest in this. Yes you are right On all fronts. Are you planning to have `HyperGraphData` inherit from `Data`, I think that should be ok to start with. 
Are you interested in sending in a PR with `HyperGraphData` and updates to `__inc__`, and `subgraph`?

**Comment by CodeTal** [comment]
> 

Sure! I am working on this. Thank you for your reply!

**Comment by CodeTal** [comment]
Sorry for the delay, I was stuck by several engineering problems related to the project. I have created a pull request #7611 which contains a HyperGraphData with `__inc__` and `subgraph` reimplemented. I found that there is no clear definition for a hypergraph's subgraph. So I chose a way to implement it (Please refer to the PR comment).

**Comment by wsad1** [comment]
Thanks @CodeTal will take a look by end of week.

**Comment by mehular0ra** [comment]
@wsad1 Hello, I am a new open-source contributor and a PyG user. Can I add a hyper graph dataset? I work on Neuroimaging data and can contribute [ABIDE2](http://fcon_1000.projects.nitrc.org/indi/abide/abide_II.html) data. I can also contribute standard datasets as well.

**Comment by wsad1** [comment]
@mehular0ra sorry for the extremely delayed reply. We'd be happy to add your dataset to pyg.

**Comment by wsad1** [comment]
@mehular0ra will open another issue to track the remaining items.
