### ISSUE TITLE
[Roadmap] Advanced Graph Sampling Routines :rocket:

### ISSUE THREAD

**Issue by motwaniravi12** [pyg-team/pytorch_geometric#7331]
### 🚀 The feature, motivation and pitch

Different GNN applications require customized sampling to improve the accuracy and/or performance. We propose the following advanced sampling routines with detailed benchmarking reports.

- **Multi-threading support**: All sampling operations are single-threaded. We can expect additional speed-ups when providing multi-threading implementation:
   - [ ] Multi-threaded `neighbor_sample` implementation
   - [x] Multi-threaded `hetero_neighbor_sample` implementation (https://github.com/pyg-team/pyg-lib/pull/215)
   - [ ] Introduce benchmarks in `pyg-lib` and/or PyG
- **Bi-directional sampling**: Allow the option to return a bidirectional graph as part of sampling (*e.g.*, for allowing GNNs with more layers than sampled hops)
   - [x] https://github.com/pyg-team/pytorch_geometric/pull/7199
   - [x] https://github.com/pyg-team/pytorch_geometric/pull/7200
   - [x] Introduce `bidirectional` sampling benchmarks 
- **Hierarchical Neighborhood sampling**: Hierarchical Neighborhood Sampling is extending classical Neighborhood Sampling by collecting additional information about number of sampled nodes and edges per each hop. That information can be used in special features like Hierarchical Graph Adjacency Matrix implemented by [`trim_to_layer`](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/trim_to_layer.py) functionality which helps to boost the performance.
    - [x] https://github.com/pyg-team/pyg-lib/pull/197
    - [x] https://github.com/pyg-team/pytorch_geometric/pull/6661
    - [x] https://github.com/pyg-team/pytorch_geometric/pull/7089
    - [x] https://github.com/pyg-team/pytorch_geometric/pull/7244
    - [x] Add automatic trimming example via a separate HGAM layer and add an example
    - [x] Write documentation/tutorial
- **Weighted Sampling**: Allow passing a `weight` vector to `neighbor_sample` to sample based on 
    - [x] Allow passing a `weight` vector to `neighbor_sample` to sample based on importance scores. [Reference DGL](https://docs.dgl.ai/generated/dgl.dataloading.NeighborSampler.html#dgl.dataloading.NeighborSampler) implementation (see `prob` argument).
    - [x] Integrate into PyG
- **Subgraph sampling**
   - [x] Initial version in `pyg-lib`, see [here]( https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/sampler/cpu/subgraph_kernel.cpp)
   - [ ] Benchmarking efforts
   - [ ] Integrate into `pyg_lib.neighbor_sample` in case `directed=False`

**Comment by xiachenrui** [comment]
Hi, `directed=False` parameter in NeighborLoader()  will  raise 'RuntimeError: Undirected subgraphs not yet supported' yet. Will this be fixed anytime soon ？

Best,
Chen-Rui

**Comment by rusty1s** [comment]
Yes, this is bullet point 3 under "Subgraph sampling".

**Comment by xiachenrui** [comment]
Happy to hear this ! I  can't wait to try it.

**Comment by rusty1s** [comment]
This routine is implemented in `torch-sparse`, so you can either do `torch_geometric.typing.WITH_PYG_LIB=False` or use the `subgraph_type="bidirectional"` argument in the meantime.

**Comment by xiachenrui** [comment]
OK, I notice the `subgraph_type` parameter  is avaliable in the latest version of docments. But the latest release (2.3.1) do not include this update.

**Comment by mfbalin** [comment]
Would there be any interest in a contribution of the following sampler from DGL?https://docs.dgl.ai/generated/dgl.dataloading.LaborSampler.html#dgl.dataloading.LaborSampler
It is basically a combination of Neighbor and Layer Sampling methods. DGL currently has a working CPU, GPU, and GPU over UVA implementation. Can be used as a drop-in replacement to `neighbor_sample` as `labor_sample`.

**Comment by rusty1s** [comment]
Thanks for the pointer. What would be needed to integrate this into PyG?

**Comment by mfbalin** [comment]
I used the pcg32 random number generator as the PRNG, given random seed z and vertex id t, `r_t = PRNG(z, t)` in the paper. So for the CPU implementation, there will be a need for either implementing or including https://github.com/imneme/pcg-cpp as a submodule. Other fast PRNGs could also be used if they are fast at generating random numbers as a function of the random seed and a given vertex id t.

An initial CPU contribution should be a fairly small PR.

**Comment by mfbalin** [comment]
My PR is here: https://github.com/pyg-team/pyg-lib/pull/242.
