### ISSUE TITLE
[Roadmap] Distributed pyg support

### ISSUE THREAD

**Issue by motwaniravi12** [pyg-team/pytorch_geometric#7333]
### 🚀 The feature, motivation and pitch

Detailed task list required to support distributed pyg are-

- [ ] Distributed arch/class definition​
- [ ] Partition/Load Partition​
- [ ] RPC/DDP APIs​
- [ ] Message Channel​
- [ ] Dist Dataset/LocalData​
- [ ] DistGraphStore/DistFeatureStore​
- [ ] DistNeighborLoader/DistLoader​
- [ ] DistNeighborSampler​
- [ ] Hetero Support​
- [ ] Unit test​
- [ ] MLPerf readiness​
-
- [ ] Distributed GPU PoC

​
