### ISSUE TITLE
Introduce PyG lifetime benchmarks

### ISSUE THREAD

**Issue by akihironitta** [pyg-team/pytorch_geometric#7795]
### 🚀 The feature, motivation and pitch

Introduce PyG lifetime benchmarks with a dashboard 🚀 (using https://github.com/airspeed-velocity/asv)

## Motivation

There are quite a number of benchmarks in PyG already:
- micro-benchmarks in `test/` (See `git grep benchmark test/`)
- macro-benchmarks in `benchmark/`

However, since the results are currently not recorded, we cannot tell whether the performance of a feature has improved or regressed over time.

## TODO

See https://github.com/pyg-team/pytorch_geometric/tree/akihironitta/bench for progress for now.

**v0**
_Introduction of a minimal set of benchmarks on CPU/GPU_
- [x] Run benchmarks manually
- [x] Run benchmarks in a CI/CD pipeline on CPU (GitHub hosted runner)
- [ ] Run benchmarks in a CI/CD pipeline on a GPU (🔴 Blocked by availability of a GPU instance)
- [x] Add micro-benchmarks (e.g. small fwd/bwd operations)

**v1**
_More expensive benchmarks, more accelerators_
- [ ] Add macro-benchmarks (e.g. training and inference)
- [ ] Support other devices (mps, xpu, rocm, ...)

## List of benchmarks and metrics

- Model benchmarks:
  - peak memory usage
  - seconds per fwd/bwd
  - seconds per training iteration
  - final target metrics (loss/precision/rocauc/etc.) after a certain number of iterations
- Operation benchmarks:
  - peak memory usage
  - seconds per fwd/bwd
- ... (open to suggestions!)

### Additional context

- PyG benchmark results will be available at https://pyg-team.github.io/pytorch_geometric/
- PyTorch Lightning results are available at https://www.akihironitta.com/lightning-benchmarks-private/
  <img width="411" alt="image" src="https://github.com/pyg-team/pytorch_geometric/assets/20610905/8292b7eb-7b01-48f6-95ce-8c175af9d3b2">

I'll modify this issue description as I make progress. Also, please feel free to modify this :)

**Comment by rusty1s** [comment]
@kiriti-kumo Can you help me with setting up GPU runners for nightly PyG runs?

**Comment by akihironitta** [comment]
@kiriti-kumo Do you know which docker image is used for the CI runner? I'm having some issues with setting up conda and mamba in [my workflow](https://github.com/pyg-team/pytorch_geometric/actions/workflows/benchmark.yml), and so I'm planning to quickly iterate on it locally.

**Comment by kiriti-kumo** [comment]
Hi @akihironitta , I don't think self-hosted Github runners use Docker container for running images. IIUC they just run the job locally as a process on the instance. We are using a GPU instance in Google Cloud with the `Ubuntu 20.04.6 LTS` OS. Are there any specific details that you'd like to know that can help your setup?
