### ISSUE TITLE
[Community Sprint] GNNs<>LLMs 🚀 

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#9694]
### 🚀 The feature, motivation and pitch

**We are kicking off another community sprint!**
This community sprint resolves around extending the latest **GNN<>LLM features** from PyG 2.6.

This sprint focuses on extending the GNN+LLM features to workflows like biology/chemistry/etc.
For examples of GNN+LLM integration in PyG, see:

1. https://github.com/pyg-team/pytorch_geometric/pull/9662: Node classification using GNNs+LLMs
2. https://github.com/pyg-team/pytorch_geometric/pull/9671: Python function name prediction on `ogbg-code2`

The sprint begins **Monday, October 14th**. If you are interested in helping out, please also join our [PyG slack](https://data.pyg.org/slack.html) channel `#gnn-plus-llm-sprint` for more information. This slack channel can serve for forming teams and discussions across teams to share ideas/knowledge.

There are four papers to work on with details [here](https://docs.google.com/spreadsheets/d/1c363ReNdK-k2arH541EFTrHmBf8psFmZTHeVDt64ghM/edit?usp=sharing).
We expect people to work in groups of 1-5. Please form teams on slack and sign up on the excel sheet.

Here are the links to the issues for each individual task:
* [x] https://github.com/pyg-team/pytorch_geometric/issues/9698
* [x] https://github.com/pyg-team/pytorch_geometric/issues/9699
* [x] https://github.com/pyg-team/pytorch_geometric/issues/9700
* [x] https://github.com/pyg-team/pytorch_geometric/issues/9701

**Comment by brovatten** [comment]
Hey @puririshi98 . I'd like to join a team on task #4, but the slack link in the excel and manually joining `#gnn-plus-llm-sprint ` isn't working for me
